[build-system]
requires = ["setuptools>=43", "wheel"]
build-backend = "setuptools.build_meta"

[tool.coverage.run]
omit = ["tests/*", "makemigrations.py", "runtests.py"]

[tool.coverage.html]
directory = "htmlcov"
