# Generated by Django 3.2.5 on 2021-09-16 18:08

from django.db import migrations, models
import django.db.models.deletion
import django_valem.utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=200)),
                ('html', models.CharField(max_length=600)),
            ],
            bases=(models.Model, django_valem.utils.models.QualifiedIDMixin),
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=80)),
                ('html', models.CharField(max_length=200)),
                ('charge', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state_type', models.SmallIntegerField(choices=[(0, 'KeyValuePair'), (1, 'GenericExcitedState'), (2, 'AtomicConfiguration'), (3, 'AtomicTermSymbol'), (4, 'DiatomicMolecularConfiguration'), (5, 'MolecularTermSymbol'), (6, 'VibrationalState'), (10, 'RotationalState'), (11, 'RacahSymbol')])),
                ('text', models.CharField(max_length=32)),
                ('html', models.CharField(max_length=100)),
                ('rp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rp.rp')),
            ],
        ),
        migrations.AddField(
            model_name='rp',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rp.species'),
        ),
    ]
