# Generated by Django 3.2.9 on 2021-11-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='text',
            field=models.CharField(max_length=64),
        ),
    ]
