# Generated by Django 3.2.9 on 2021-11-30 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rp', '0002_alter_species_charge'),
        ('rp', '0002_alter_state_text'),
    ]

    operations = [
    ]
